# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RAL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LB1 = QtWidgets.QLabel(self.centralwidget)
        self.LB1.setFrameShape(QtWidgets.QFrame.Box)
        self.LB1.setText("")
        self.LB1.setObjectName("LB1")
        self.horizontalLayout.addWidget(self.LB1)
        self.LB2 = QtWidgets.QLabel(self.centralwidget)
        self.LB2.setFrameShape(QtWidgets.QFrame.Box)
        self.LB2.setText("")
        self.LB2.setObjectName("LB2")
        self.horizontalLayout.addWidget(self.LB2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PB = QtWidgets.QPushButton(self.centralwidget)
        self.PB.setMinimumSize(QtCore.QSize(0, 360))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB.setFont(font)
        self.PB.setObjectName("PB")
        self.verticalLayout.addWidget(self.PB)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.ControlW = QtWidgets.QWidget(self.centralwidget)
        self.ControlW.setMinimumSize(QtCore.QSize(330, 0))
        self.ControlW.setMaximumSize(QtCore.QSize(330, 16777215))
        self.ControlW.setObjectName("ControlW")
        self.horizontalLayout_2.addWidget(self.ControlW)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PB.setText(_translate("MainWindow", "PushButton"))
